name: CI/CD

on:
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
